/// <reference types="bun" />
import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createHash } from "node:crypto";

import {
  generateRunnerExecutionAssets,
  readCanonicalBunVersionFromReleaseWorkflow,
} from "./generate-runner-execution-assets";

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function tempRoot(name: string): string {
  const root = mkdtempSync(join(tmpdir(), name));
  roots.push(root);
  return root;
}

function workflow(version: string): string {
  return `jobs:
  release-verification:
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "${version}"
  build:
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "${version}"
`;
}

const fixtureEntries = [
  ["opencode", "packages/adapter-opencode/assets/opencode/plugins/developer-team-execution"],
  ["pi", "packages/adapter-pi/assets/pi/extensions/developer-team-execution"],
  ["codex", "packages/adapter-codex/assets/codex/hooks/developer-team-execution"],
] as const;

function writeGeneratorFixture(root: string, version: string): Record<string, string> {
  mkdirSync(join(root, ".github", "workflows"), { recursive: true });
  writeFileSync(join(root, ".github", "workflows", "release.yml"), workflow(version));
  const outputs: Record<string, string> = {};
  for (const [adapter, pathWithoutExt] of fixtureEntries) {
    const entry = join(root, `${pathWithoutExt}.ts`);
    const output = join(root, `${pathWithoutExt}.generated.js`);
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(entry, `export const adapter = ${JSON.stringify(adapter)};\nexport default function run() { return adapter; }\n`);
    writeFileSync(output, `sentinel:${adapter}`);
    outputs[adapter] = output;
  }
  return outputs;
}

function fileContents(paths: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(paths).map(([key, path]) => [key, readFileSync(path, "utf8")]));
}

describe("generate-runner-execution-assets canonical Bun guard", () => {
  test("binds the generator guard to the release workflow Bun version contract", () => {
    expect(readCanonicalBunVersionFromReleaseWorkflow(process.cwd())).toBe("1.3.12");

    const root = tempRoot("deck-runner-assets-workflow-guard-");
    mkdirSync(join(root, ".github", "workflows"), { recursive: true });
    writeFileSync(join(root, ".github", "workflows", "release.yml"), workflow("9.8.7"));

    expect(readCanonicalBunVersionFromReleaseWorkflow(root)).toBe("9.8.7");
  });

  test("rejects a non-canonical executing Bun before mutating any generated output", () => {
    const root = tempRoot("deck-runner-assets-wrong-bun-");
    const wrongVersion = Bun.version === "0.0.0" ? "9.9.9" : "0.0.0";
    const outputs = writeGeneratorFixture(root, wrongVersion);
    const before = fileContents(outputs);

    expect(() => generateRunnerExecutionAssets({ root })).toThrow(/No outputs were written/);

    expect(fileContents(outputs)).toEqual(before);
  });

  test("uses the executing Bun binary for builds so PATH cannot select a different child", () => {
    const root = tempRoot("deck-runner-assets-exec-bun-");
    const outputs = writeGeneratorFixture(root, Bun.version);
    const fakeBin = tempRoot("deck-runner-assets-fake-path-");
    const marker = join(fakeBin, "fake-bun-was-used");
    writeFileSync(join(fakeBin, "bun"), `#!/bin/sh\nprintf used > ${JSON.stringify(marker)}\nexit 42\n`);
    chmodSync(join(fakeBin, "bun"), 0o755);
    const previousPath = process.env.PATH;
    process.env.PATH = `${fakeBin}:${previousPath ?? ""}`;
    try {
      const results = generateRunnerExecutionAssets({ root });

      expect(results.map((result) => result.bunPath)).toEqual([process.execPath, process.execPath, process.execPath]);
    } finally {
      process.env.PATH = previousPath;
    }

    expect(existsSync(marker)).toBe(false);
    for (const [adapter, pathWithoutExt] of fixtureEntries) {
      const source = readFileSync(join(root, `${pathWithoutExt}.ts`));
      const generated = readFileSync(outputs[adapter], "utf8");
      expect(generated).toContain("Generated by scripts/generate-runner-execution-assets.ts; do not edit.");
      expect(generated).toContain(`source-sha256:${createHash("sha256").update(source).digest("hex")}`);
      expect(generated).toContain(JSON.stringify(adapter));
    }
  });
});
